# app/schemas/ai_chat.py
"""Pydantic schemas for the AI chat endpoint.

These schemas are used by the FastAPI routes and by the AIOrchestrator service.
They are deliberately lightweight and future‑compatible (optional streaming,
tool‑calling, RAG etc.).
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field, ConfigDict


class Usage(BaseModel):
    """Token‑usage information returned by a provider."""

    prompt_tokens: int = Field(..., description="Number of tokens sent to the provider")
    completion_tokens: int = Field(..., description="Number of tokens generated by the provider")
    total_tokens: int = Field(..., description="Sum of prompt and completion tokens")

    model_config = ConfigDict(extra="forbid")


class AIChatRequest(BaseModel):
    """Incoming request from the Chat API."""

    conversation_id: int = Field(..., description="Identifier of the conversation")
    message: str = Field(..., description="User message to send to the LLM")
    stream: bool = Field(False, description="Whether the response should be streamed")
    provider: Optional[str] = Field(
        None,
        description="Explicit provider name (e.g. 'groq', 'openai'). If omitted the orchestrator resolves it automatically.",
    )
    model: Optional[str] = Field(
        None,
        description="Explicit model name. Resolved hierarchically if not supplied.",
    )

    model_config = ConfigDict(extra="ignore")


class AIChatResponse(BaseModel):
    """Standardised response returned by the Chat API."""

    conversation_id: int = Field(..., description="Conversation identifier")
    assistant_message: str = Field(..., description="Message generated by the LLM")
    provider: str = Field(..., description="Provider that produced the response")
    model: str = Field(..., description="Model name used for generation")
    usage: Usage = Field(..., description="Token usage details")
    finish_reason: str = Field(..., description="Why the generation stopped (e.g. 'stop', 'length')")

    model_config = ConfigDict(extra="ignore")
