"""
Chat Engine schemas.

Defines all Pydantic v2 request and response models for the Chat Engine REST API.
These schemas are provider-agnostic and future-compatible with streaming, tool
calling, RAG, and memory modules.

Design decisions:
  - ChatBaseRequest holds every shared optional override field.
  - Each endpoint gets its own concrete request class for clarity.
  - ChatResponseSchema is the single normalised response for all POST endpoints.
  - ConversationDetailSchema covers the GET endpoint with pagination.
  - MessageSchema serialises persisted Message rows including all metadata columns.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


# ---------------------------------------------------------------------------
# Shared sub-models
# ---------------------------------------------------------------------------


class UsageSchema(BaseModel):
    """Token usage details returned for every AI invocation."""

    model_config = ConfigDict(extra="forbid")

    prompt_tokens: int = Field(0, description="Tokens sent to the provider")
    completion_tokens: int = Field(0, description="Tokens generated by the provider")
    total_tokens: int = Field(0, description="Sum of prompt and completion tokens")


class AssistantMessageSchema(BaseModel):
    """Lightweight representation of a persisted assistant message."""

    model_config = ConfigDict(extra="forbid")

    id: int = Field(..., description="Database ID of the persisted message")
    role: str = Field("assistant", description="Always 'assistant'")
    content: str = Field(..., description="Text generated by the model")
    provider: Optional[str] = Field(None, description="Provider that generated this message")
    model_used: Optional[str] = Field(None, description="Model used for this message")
    finish_reason: Optional[str] = Field(None, description="Why generation stopped")
    prompt_tokens: Optional[int] = Field(None, description="Prompt token count")
    completion_tokens: Optional[int] = Field(None, description="Completion token count")
    total_tokens: Optional[int] = Field(None, description="Total token count")
    created_at: datetime = Field(..., description="UTC timestamp of creation")


# ---------------------------------------------------------------------------
# Request models
# ---------------------------------------------------------------------------


class ChatBaseRequest(BaseModel):
    """
    Shared fields for all chat request variants.

    provider and model are optional — when omitted the AI Orchestrator
    resolves them automatically via agent defaults and failover logic.
    """

    model_config = ConfigDict(extra="forbid")

    message: str = Field(
        ...,
        min_length=1,
        max_length=32_768,
        description="User message to deliver to the agent",
    )
    provider: Optional[str] = Field(
        None,
        description="Override provider name (e.g. 'groq', 'openai'). Orchestrator decides when omitted.",
    )
    model: Optional[str] = Field(
        None,
        description="Override model name. Agent default used when omitted.",
    )
    temperature: Optional[float] = Field(
        None,
        ge=0.0,
        le=2.0,
        description="Sampling temperature override (0.0–2.0)",
    )
    top_p: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description="Nucleus sampling top-p override",
    )
    max_tokens: Optional[int] = Field(
        None,
        gt=0,
        description="Maximum number of completion tokens",
    )
    stream: bool = Field(
        False,
        description="Request a streaming response (reserved — not yet active)",
    )
    # Future-compatibility placeholder
    tool_choice: Optional[str] = Field(
        None,
        description="Tool selection mode — reserved for Tool Calling module",
    )


class ChatCreateRequest(ChatBaseRequest):
    """
    Request body for POST /api/v1/chat.

    Creates a brand-new conversation and returns the first assistant message.
    agent_id is required to bootstrap the conversation.
    """

    agent_id: int = Field(..., description="ID of the agent to bootstrap the conversation")


class ChatContinueRequest(ChatBaseRequest):
    """
    Request body for POST /api/v1/chat/{conversation_id}.

    Continues an existing conversation with a new user message.
    """


class ChatRegenerateRequest(BaseModel):
    """
    Request body for POST /api/v1/chat/{conversation_id}/regenerate.

    Creates a *new* assistant message without re-sending a user message.
    Provider / model overrides are supported.
    """

    model_config = ConfigDict(extra="forbid")

    provider: Optional[str] = Field(None, description="Override provider for this regeneration")
    model: Optional[str] = Field(None, description="Override model for this regeneration")
    temperature: Optional[float] = Field(None, ge=0.0, le=2.0)
    top_p: Optional[float] = Field(None, ge=0.0, le=1.0)
    max_tokens: Optional[int] = Field(None, gt=0)
    stream: bool = Field(False)


class ChatRetryRequest(BaseModel):
    """
    Request body for POST /api/v1/chat/{conversation_id}/retry.

    Re-executes the AI Orchestrator for the last *failed* assistant message.
    No duplicate user messages are created.
    """

    model_config = ConfigDict(extra="forbid")

    provider: Optional[str] = Field(None, description="Override provider for retry")
    model: Optional[str] = Field(None, description="Override model for retry")


class ConversationQueryParams(BaseModel):
    """Pagination parameters for GET /api/v1/chat/{conversation_id}."""

    model_config = ConfigDict(extra="forbid")

    page: int = Field(1, ge=1, description="1-based page number")
    page_size: int = Field(20, ge=1, le=200, description="Number of messages per page")


# ---------------------------------------------------------------------------
# Response models
# ---------------------------------------------------------------------------


class ChatResponseSchema(BaseModel):
    """
    Normalised response returned by all POST chat endpoints.

    Future-compatible: extend with `tool_calls`, `citations`, `memory_id`
    without breaking existing consumers.
    """

    model_config = ConfigDict(extra="ignore")

    conversation_id: int = Field(..., description="Identifier of the conversation")
    assistant_message: AssistantMessageSchema = Field(..., description="The generated assistant message")
    provider: str = Field(..., description="Provider that produced the response")
    model: str = Field(..., description="Model used for generation")
    usage: UsageSchema = Field(..., description="Token usage details")
    finish_reason: str = Field(..., description="Why generation stopped (e.g. 'stop', 'length')")
    created_at: datetime = Field(..., description="UTC timestamp of the response")


class MessageSchema(BaseModel):
    """Single persisted message within a conversation."""

    model_config = ConfigDict(extra="ignore")

    id: int
    role: str
    content: str
    provider: Optional[str] = None
    model_used: Optional[str] = None
    finish_reason: Optional[str] = None
    prompt_tokens: Optional[int] = None
    completion_tokens: Optional[int] = None
    total_tokens: Optional[int] = None
    created_at: datetime


class ConversationDetailSchema(BaseModel):
    """
    Returned by GET /api/v1/chat/{conversation_id}.

    Provides paginated message history plus conversation metadata.
    """

    model_config = ConfigDict(extra="ignore")

    conversation_id: int
    title: Optional[str]
    agent_id: int
    organization_id: int
    user_id: int
    messages: list[MessageSchema]
    page: int
    page_size: int
    total_messages: int
    created_at: datetime
    updated_at: datetime
