"""
Message database model.

Extended with AI provenance metadata columns so that every assistant
turn carries full observability data (provider, model, tokens, finish_reason).
"""

from sqlalchemy import ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base
from app.models.base_model import BaseModel


class Message(Base, BaseModel):
    """
    Represents a message inside a conversation.

    Columns:
      - role           : 'user', 'assistant', or 'system'
      - content        : raw text of the message
      - provider       : AI provider that generated assistant messages (nullable)
      - model_used     : exact model name used for generation (nullable)
      - finish_reason  : why generation stopped — 'stop', 'length', etc. (nullable)
      - prompt_tokens  : number of tokens in the prompt (nullable)
      - completion_tokens: tokens generated by the model (nullable)
      - total_tokens   : sum of prompt + completion (nullable)
    """

    __tablename__ = "messages"

    conversation_id: Mapped[int] = mapped_column(
        ForeignKey(
            "conversations.id",
            ondelete="CASCADE",
        ),
        nullable=False,
        index=True,
    )

    role: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )

    content: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    # -------------------------------------------------------------------------
    # AI provenance metadata (nullable — populated only for assistant messages)
    # -------------------------------------------------------------------------

    provider: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
    )

    model_used: Mapped[str | None] = mapped_column(
        String(200),
        nullable=True,
    )

    finish_reason: Mapped[str | None] = mapped_column(
        String(50),
        nullable=True,
    )

    prompt_tokens: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )

    completion_tokens: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )

    total_tokens: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )

    # -------------------------------------------------------------------------
    # Relationships
    # -------------------------------------------------------------------------

    conversation = relationship(
        "Conversation",
        back_populates="messages",
    )

    def __repr__(self) -> str:
        return f"<Message(id={self.id}, role='{self.role}')>"
